[package]
name = "devflow-gh"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
devflow-core = { path = "../devflow-core" }

[dev-dependencies]
toml.workspace = true
